name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.build.outputs.artifact-path }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare site (optional)
        run: |
          # For a static site without build step, ensure public/ exists
          mkdir -p public
          echo "<!DOCTYPE html><html><body><h1>DeepDIP Docs Coming Soon</h1></body></html>" > public/index.html
      - name: Upload Pages Artifact
        id: build
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
